"""empty message

Revision ID: 41bedec558de
Revises: 03ba30edd5dd
Create Date: 2022-09-01 01:29:12.962575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bedec558de'
down_revision = '03ba30edd5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gravatar_hash',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gravatar_hash',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
