"""empty message

Revision ID: e03e953402e8
Revises: eb2ca62ccffc
Create Date: 2022-08-29 16:23:22.562883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03e953402e8'
down_revision = 'eb2ca62ccffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gravatar_hash', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gravatar_hash')
    # ### end Alembic commands ###
